<!DOCTYPE html>
<?php include('header.php');?>

    <div class="container">

        <div class="bg-faded p-4 my-4">
          <!-- post 1-->
          <div class="bg-faded p-4 my-4">
            <div class="text-center mt-4">

                  <h2 class="my-2">La tradición, el patrimonio y la identidad</h2>
                  <div class="bg-faded p-4 my-4">
                              <hr class="divider">
                              <h3 class="text-center text-lg text-uppercase my-0">Javier Marcos Arévalo</h3>
                              <hr class="divider">

                              <p> Los bienes culturales, son definidos y a la vez definen, su valor cultural, en una dimensión material (técnicas, procesos de trabajo, contexto) y por otra parte en sus usos, funciones, en  sus significados. Estos bienes de patrimonio se enfrentan en su valor de uso, su identidad, y su valor de cambio, su presencia en el mercado, donde su identidad, representa su relación con la comunidad y la memoria colectiva del territorio, que se ve amenazada por la comercialización de estos en usos turísticos, pero en muchos casos, es un agente que permite la mantención de una tradición en el tiempo. </p>
                          <p>Revisa el texto original <a href="http://www.dip-badajoz.es/cultura/ceex/reex_digital/reex_LX/2004/T.%20LX%20n.%203%202004%20sept.-dic/RV000002.pdf">aqui</a></p>
                                      <img class="img-fluid float-center hidden-md-down " src="img/productor.jpg" alt="">
                                      <hr></div></div>

                                      <div class="cuerpo p-4"> <p>Resumen

<hr>Enfocado desde la perspectiva de la antropología social, el artículo se estructura en torno a los conceptos de tradición, bienes culturales intangibles y representación de la memoria social. Desde planteamientos críticos el trabajo revisa textos fundamentales y analiza y valora los documentos que sobre patrimonio inmaterial ha hecho público la UNESCO en los últimos quince años.

<hr>"Una tradición verdadera no es testimonio de un pasado caduco; es fuerza viva que anima e informa el presente. Lejos de implicar la repetición de lo que fue, la tradición supone la realidad de lo que perdura… Un patrimonio que se recibe a condición de hacerlo fructificar antes de transmitirlo a los descendientes". (Igor Stravinsky, Poética musical, París, 1952).

<hr>Introducción

<hr>El espíritu y el texto completo de la "Convención sobre la protección y promoción de la diversidad de las expresiones culturales"2, van encaminados a la salvaguarda de la diversidad cultural frente a la homogeneización que orienta la mundialización. El texto condensa, básicamente, las siguientes ideas: 1ª.- La cultura adquiere formas diversas a través del tiempo y del espacio. 2ª.- La protección y promoción de la diversidad de las expresiones culturales presuponen el reconocimiento de la igual dignidad de todas las culturas. 3ª.- Considera el patrimonio cultural inmaterial como elemento fundamental de la identidad. 4ª.- Y la diversidad cultural como uno de los motores del desarrollo sostenible de las comunidades, los pueblos y los grupos sociales. Y 5ª.- Con el documento se pretende contribuir a promover el respeto y el diálogo entre las culturas, así como a fomentar la interculturalidad.

<br>Desde una concepción dinámica, alejada de la retórica de la nostalgia por el pretérito, hay que entender el patrimonio como recurso, pero también como proceso vivo, y no como algo inmovilista… Los bienes culturales, tangibles o intangibles, no son residuos de un tiempo pasado que hay que conservar en un supuesto modelo ideal. Por ejemplo las manifestaciones vivas, representaciones significativas de la tradición, continuamente están reproduciéndose en un proceso inacabado de transmisión.

<br>Hay que convenir que el patrimonio, como resultado de una construcción social, refiere un conjunto de bienes culturales que reciben una valoración positiva por parte de la sociedad, cuya identidad expresan, en el sentido que es un elemento mediante el que se establece la diferencia con los otros grupos sociales y culturales; pero representa, asimismo, un factor de resistencia contra los embates de la uniformización. El patrimonio, una especie de simbología social para el mantenimiento y la transmisión de la memoria colectiva, está constituido por los bienes representativos de cada sociedad. Y se puede afirmar que los fenómenos patrimoniales revisten una triple dimensión:

<br>física, social y mental; es decir, material y simbólica. Sobre esta cuestión, específicamente relacionado con el peso de lo ideal y lo material en la construcción de la sociedad y de las realidades sociales, es sugerente la obra al respecto de Maurice Godelier3.

<br>El patrimonio intangible está en todos los aspectos de los bienes culturales. Y es la base de la identidad, la creatividad y la diversidad cultural. Es un patrimonio vivo, continuamente recreándose, que cobra vida a través de los seres humanos y de sus prácticas y formas de expresión. Mediante las manifestaciones patrimoniales significativas la gente recuerda y reconoce su pertenencia a un grupo social y a una comunidad; si bien la identidad cultural no es sólo una, sino múltiple, y siempre relacional y contextual; es decir, dinámica y procesual.

<hr>La tradición

<hr>La cultura, las formas de vida materiales, sociales e ideacionales de las sociedades, los pueblos y los grupos sociales, es a la vez universal y particular, múltiple y diversa en la experiencia humana. La tradición equivale al concepto de cultura como la conciben los antropólogos: un sistema integrado dialécticamente por subsistemas interrelacionados: lo material (infraestructura: las relaciones que se establecen entre los hombres y el medio), lo conductual-social (la estructura: las relaciones que construyen y mantienen los hombres y las mujeres entre sí) y lo mental-simbólico (la superestructura: las relaciones que se dan entre los hombres y el más allá, lo sobrenatural).

<br>Actualmente asistimos a una profunda revisión o reificación del concepto de tradición desde una renovada perspectiva. La tradición es una construcción social que cambia temporalmente, de una generación a otra; y espacialmente, de un lugar a otro. Es decir, la tradición varía dentro de cada cultura, en el tiempo y según los grupos sociales; y entre las diferentes culturas.

Lo tradicional refiere, en general, aunque no en exclusiva, a las clases y sectores sociales rurales (especialmente a los grupos agrícolas y campesinos) y a los obreros en el medio urbano; si bien la tradición existe en todas partes. Todos los grupos sociales, urbanos o rurales, tienen tradición. En la ciudad también se dan manifestaciones tradicionales provenientes del mundo rural a través de la emigración. Es decir, existe una cultura tradicional, más allá del mundo rural, en el medio urbano. De manera que los obreros industriales, los arquitectos, los empresarios, los juristas, los profesionales de la enseñanza, los comerciantes, la burguesía, la aristocracia, etc., poseen peculiares formas de expresión económicas, sociales e ideacionales, en suma, tradiciones diferenciadas a través de sus propias experiencias existenciales. Valgan como ejemplo las ceremonias y los rituales universitarios que se escenifican, según usos y tradiciones particulares, cuando se obtienen los grados de licenciatura, doctorado, o cuando se formaliza el ascenso al estatus de funcionario. Rangos que se acompañan de elementos intangibles, como el tratamiento especial que se dispensa a quienes los obtienen; pero también materiales como los que simbolizan determinados colores de la indumentaria ceremonial, togas, birretes, anillos, etc.; lo que del mismo modo puede trasladarse a la actividad de políticos, juristas y a otros profesionales y actividades sociolaborales.
<br>La idea común que se tiene sobre la tradición es la que etimológicamente hace venir el término del latín "tradere", del que derivaría tradición, o sea lo que viene transmitido del pasado; por extensión, el conjunto de conocimientos que cada generación entrega a la siguiente. Pero este significado originario está sufriendo diversas transformaciones. Si la tradición es la herencia del tiempo social en la memoria colectiva, el legado del pasado, lo es también debido a su renovación en el presente; porque la tradición, la transmisión de la cultura entre las generaciones, se construye a partir de la contemporaneidad. La tradición cobra pleno sentido cuando los contemporáneos la reviven y de este modo se la apropian. La tradición, de hecho, actualiza y renueva el pasado desde el presente. La tradición, para mantenerse vigente, y no quedarse en un conjunto de anacrónicas antiguallas o costumbres fósiles y obsoletos testimonios, se modifica al compás de la sociedad, pues representa la continuidad histórica y la memoria colectiva. Integra el pasado, seleccionado, y el presente, en el futuro, en vez de sustituirlo. De manera que la noción de tradición evoca la idea de un cierto modo de transmisión, de nexo entre generaciones. De aquí, justamente, su versátil capacidad de cambio y de adaptación cultural. La tradición, para ser funcional, está en constante renovación, y se crea, recrea, inventa y destruye cada día4. Porque la tradición contiene en sí misma los gérmenes de la estabilidad, la continuidad, y el cambio, la discontinuidad. Y el cambio, en términos de adaptación sociocultural, es consustancial a toda sociedad; continuamente se crean formas nuevas de expresión cultural.

<br>Frente a la esencialista, restrictiva y tradicional noción de tradición, convencionalmente figurada como estática, inalterable y pretérita, algunos antropólogos han sugerido la necesidad de proceder a la resemantización de sus significados en el contexto más comprensivo que supone la teoría del cambio cultural. De manera que la tradición sería ahora algo así como el resultado de un proceso evolutivo inacabado con dos polos dialécticamente vinculados: la continuidad recreada y el cambio. La idea de tradición remite al pasado pero también a un presente vivo. Lo que del pasado queda en el presente eso es la tradición. La tradición sería, entonces, la permanencia del pasado vivo, la memoria colectiva, en el presente. Supone un proceso y un resultado, pues simultáneamente es un proceso de producción, transmisión y reproducción. De tal manera la tradición, vehículo de memoria, se adapta y recrea; porque la tradición por su característica de fluidez y permeabilidad vincula a la gente con su historia, es decir con la memoria colectiva. Las personas vienen y se van, pero la cultura perdura en la medida que una generación la transmite a la siguiente5.

<br>La tradición no se hereda genéticamente; se transmite socialmente y deriva de un proceso de selección cultural. La parte de la cultura seleccionada en el tiempo con   una función de uso en el presente sería la tradición. El pasado, decantado, es continuamente reincorporado al presente. Desde tal punto de vista la tradición implica una cierta selección de la realidad social. Y aunque la tradición es un hecho de permanencia de una parte del pasado, no todo el pasado que sobrevive en el presente es o se convierte mecánicamente en tradición. Invirtiendo los planteamientos convencionales Gerard Lenclud considera que no es el pasado el que produce el presente, sino a la inversa, el presente quien configura el pasado6. La tradición, de tal modo, más que madre es hija del presente.
La tradición, para seguir siéndolo, implica unas tasas de transformación, en términos de adaptación sociocultural, para su reproducción y mantenimiento. La tradición y el cambio no son categorías antinómicas, remiten a un sistema dialéctico de oposiciones binarias complementarias. El soporte del cambio suele ser la tradición y, parte de ella, se encuentra incorporada a los resultados del proceso de cambio, la continuidad. Ahora bien, tradición e innovación son categorías que están unidas mecánicamente. Continuar sin renovar es sólo repetir, mientras que innovar, sin el soporte del pasado, de la experiencia vivencial, puede equivaler a hacer castillos de naipes o a construirlos en la arena. Sería como quedarse sin asideros, pues la tradición pauta la conducta. Cualquier cambio se produce sobre un fondo de continuidad y cualquier permanencia incorpora variaciones. Consecuentemente la tradición no consiste en la reproducción, o el calco prístino, del supuesto patrón original, porque la réplica del pasado no se realiza con toda fidelidad. La tradición en conjunto, o en cualquiera de sus ámbitos referenciales, como por ejemplo la literatura de tradición oral, el cancionero o la música popular específicamente, se recrea permanentemente perviviendo no tanto en un imaginario o especulado primer modelo, que no existe, como en versiones y variantes. La innovación, el cambio, opera actualizando el texto, la tradición. Es decir, es un proceso inacabado de creación-recreación, producción-reproducción, continuidad-discontinuidad; un sistema en constante renovación. Asumida la tradición desde tal punto de vista hay que poner en cuestión la idea que, sesgadamente, temporaliza, tradicionaliza y arqueologiza, cuando no fetichiza, la tradición. De manera que la tradición no es inalterable, sino dinámica y adaptativa. Desde una mirada utilitarista la tradición, el conjunto de respuestas culturales que sirven para resolver los problemas existenciales (materiales, sociales e ideacionales), se usa activamente, pues cumple funciones sociales y tiene significados.

<br>En la tradición, el nexo de continuidad entre el pasado y el presente, existe un aspecto permanente y otro susceptible al cambio. La tradición, además, resulta de un proceso de decantación cultural y de hibridación que deriva del pasado transformado y de su incorporación en el presente. Cada comunidad, colectivo, grupo humano, social…, por otra parte, construye y recrea su tradición en función de diferentes experiencias existenciales. Es decir, cada grupo específico, con una experiencia histórica colectiva, posee una cultura o tradición propia7.

<br>Existe una idea restrictiva y errónea sobre la cultura tradicional. Refiere a la falsedad del esquema dualista de la sociedad: sociedad tradicional/sociedad moderna, como quiso presentarla Robert Redfield, modificado posteriormente por el también antropólogo estadounidense George M. Foster. Hoy está generalmente aceptado que no se dan dos sociedades diferentes e independientes, una tradicional (¿supuestamente popular…?) y otra moderna (¿culta…?). Un reflejo más próximo a la realidad muestra una imagen dialéctica de las culturas, en relación de oposición/complementariedad. Es decir, parece que lo tradicional y lo moderno forman parte de un mismo sistema y se dan en una única sociedad global. En todo caso de lo que se trata es de dos experiencias distintas. Ahora bien, como observara Néstor García Canclini (1989) cada día es mayor el grado de hibridación entre lo tradicional y lo moderno, cuyo resultado es lo que convenimos en llamar culturas de masas.

<hr>Los bienes culturales intangibles

<hr>Los logros y progresos humanos derivan de los bienes intangibles, del conocimiento, dado que son las ideas las que motivan a las personas a crear el patrimonio, material o inmaterial. Razón por la que hay que valorar, más que los productos y las creaciones, a los productores y creadores8.

<br>Aunque habitualmente se establece una separación instrumental entre el patrimonio material e inmaterial, existe cierta dificultad para disociarlos, hasta tal punto que a veces se torna algo arbitrario o resulta artificial. Los valores culturales intrínsecos de los bienes culturales derivan, por una parte, de su dimensión material (los procesos de trabajo y las técnicas, las habilidades, el diseño y el marco contextual); y de otra, de los usos y las funciones, así como de los significados. De tal suerte tan sólo operativamente podemos desligar lo material de lo inmaterial; pues los bienes culturales deben valorarse de una manera interrelacionada. De hecho el patrimonio material refiere en sí mismo todo un conjunto de formas de vida, creencias, valores, emociones y significados que proporcionan sentimiento de identidad y pertenencia. De manera que el patrimonio cultural inmaterial no puede substraerse totalmente del patrimonio material. Ahora bien, algunas características los diferencian: el patrimonio inmaterial suele ser un patrimonio vivo y por ello en continua transformación; se transmite de generación en generación, intergeneracionalmente, y está permanentemente variando. Porque siempre la transmisión de los conocimientos y los procesos sociales de aprendizaje, por ejemplo las técnicas de las artesanías, o las prácticas y los usos sociales, rituales, etc., son inmateriales y se hace por vía oral, mediante la lengua, el gesto o la imitación. "La artesanía es material, no inmaterial. Pero la transmisión se hace por vía oral. En la artesanía, por ejemplo, está el objeto; pero también el trabajo sobre el objeto, que son la palabra, los gestos, las técnicas, los ritos…"9.

<br>Los bienes culturales materiales e inmateriales no pueden disociarse, pues refieren categorías contiguas. Todo lo material tiene un sustrato inmaterial. De hecho los objetos materiales son el resultado de los conocimientos, las normas y los valores que prevalecen en cada cultura y grupo social. Y todos, en la práctica, incorporan saberes, técnicas y significados. Lo importante, entonces, no son tanto los productos como los procesos, es decir la transmisión del conocimiento, antes que la conservación de los objetos. Existen sin embargo, como observara Koichiro Matsuura, otros bienes del patrimonio cultural inmaterial que no guardan relación directa con el patrimonio material, tales como las tradiciones orales, las lenguas, los cantos, las danzas, los ritos, las fiestas y las prácticas sociales10. Pero incluso en estos casos la inmaterialidad se expresa también mediante elementos materiales; por ejemplo, las creencias se expresan a través de las imágenes, los exvotos y promesas, lampadarios...; las lenguas mediante su expresión escrita; la música y los cantos, por medio de su representación en el pentagrama y otros sistemas de transcripción; las danzas, a través de la indumentaria y los instrumentos musicales, etc.

<br>Una visión más antropológica del patrimonio se interesa menos por las formas que reviste que por los usos, los valores y los significados. El patrimonio significa herencia viva que confiere sentido de continuidad, dado que vincula las generaciones anteriores con las posteriores. El valor patrimonial deriva de su capacidad como referente de un modo de vida. Y los objetos, o los bienes culturales tangibles, interesan como documentos, puesto que sirven para construir un discurso social y elaborar una reflexión antropológica sobre el patrimonio.

<br>El patrimonio inmaterial, herencia que se transmite, también experimenta cambios creándose, recreándose o inventándose; puesto que es un patrimonio en uso, de cuya característica deriva su capacidad de transformación y el vínculo que establece entre generaciones; un nexo de transmisión temporal. La UNESCO, desde 1992, acepta la necesidad de reconocer las tradiciones vivas, que se transmiten oralmente, mediante los gestos y por imitación. En el carácter vivo y efímero de este patrimonio, así como en su medio de transmisión, la oralidad y la práctica, radica justamente su fragilidad.

<br>El concepto de "monumentalidad", en concordancia con las ideas anteriores, no sirve para valorar los bienes culturales de carácter inmaterial. La especificidad de los bienes etnológicos es, por una parte, el estar vivos, y de otra, la imbricación entre lo material y lo inmaterial. Lo que importa para que una cultura esté viva no son los objetos, sino el conocimiento y la información que se posea sobre ellos.

<br>Los significados que encierran los bienes culturales intangibles son producto de la herencia cultural; pero igual que las formas que adoptan, y aún permaneciendo éstas en el tiempo, los significados se modifican. Como la cultura los bienes intangibles, las formas de vida representativas de los grupos sociales, se revitalizan con la transmisión que continuamente se experimenta entre las generaciones; porque a diferencia del patrimonio monumental los bienes intangibles suelen ser dinámicos y por naturaleza están en constante evolución.

<br>El Programa de la UNESCO sobre los Tesoros Humanos Vivos, iniciado en 1993, se refiere a los individuos que poseen habilidades y técnicas necesarias para producir determinados elementos de la vida cultural de un pueblo o grupo social y mantener así la existencia de su patrimonio cultural inmaterial. El saber y las habilidades se transmiten generacionalmente. En las artes interpretativas, la música, el baile, el drama, el teatro, los ritos, etc., el acto mismo de la creación y de la interpretación no tiene forma física, son obras intangibles. Y lo mismo podría decirse respecto a las lenguas, instrumentos de comunicación, pero factor también de identidad de los grupos humanos. El objetivo del programa de tesoros humanos vivos es el de que cada Estado miembro de la UNESCO trate de preservar las destrezas y las técnicas para la manifestación y transmisión de las expresiones culturales que cada Estado considere más significativas. Como se sabe, en 1999 la UNESCO puso en marcha la distinción Obras Maestras del Patrimonio Oral e Inmaterial de la Humanidad. Y en París, en el 2003, aprobó la Convención para la salvaguardia del patrimonio cultural inmaterial. Documento en el que el patrimonio inmaterial se define de la siguiente manera:

<br>Se entiende por patrimonio cultural inmaterial los usos, representaciones, expresiones, conocimientos y técnicas… que las comunidades, los grupos y en algunos casos los individuos reconozcan como parte integrante de su patrimonio cultural. Este patrimonio cultural inmaterial, que se transmite de generación en generación, es recreado constantemente por las comunidades y grupos en función de su entorno, su interacción con la naturaleza y su historia, infundiéndoles un sentido de identidad y continuidad…11.

<br>Tres son las principales cuestiones que trata la Convención: 1ª.- Las finalidades: (salvaguardia del patrimonio cultural inmaterial, sensibilizar sobre el respeto al patrimonio cultural inmaterial y subraya la importancia que posee para los grupos sociales). 2ª.- Los ámbitos de manifestación del patrimonio intangible: (las tradiciones y expresiones orales, las artes del espectáculo, los usos sociales, rituales y los actos festivos, los conocimientos y usos relacionados con la naturaleza y el universo y las técnicas artesanales tradicionales). 3ª.- Las medidas para su salvaguardia: (identificación de las manifestaciones, de sus depositarios y conocedores, documentación mediante la tecnología apropiada para transformar los bienes en soporte material y audiovisual; investigación, preservación y protección; promoción y valorización, la transmisión y la revitalización).

<br>El texto de la Convención sugiere que cada Estado miembro debe fomentar el inventario del patrimonio cultural intangible y su estudio en los respectivos territorios; así como la creación de instituciones para la documentación de los bienes culturales inmateriales. La UNESCO, aparte, recomienda algunas prácticas para la salvaguardia del patrimonio inmaterial:

<br>1.- La necesaria sensibilización/concienciación de la importancia, como fuente de riqueza material e inmaterial, de la diversidad cultural. Asume los bienes culturales patrimoniales como fuente de creatividad y diversidad cultural.

<br>2.- La preservación de su función en la vida colectiva y la naturaleza interpersonal de su transmisión.

<br>3.- El refuerzo del aprendizaje y la transmisión del conocimiento y de las técnicas (Inclusión en los currícula escolares en los sistemas educativos. Y en los programas de formación informal en talleres y oficios: de maestro a aprendiz o discípulo).

<br>4.- El asumir las tradiciones, los bienes culturales intangibles, como procesos más que como productos.

<br>5.- La aplicación de las nuevas tecnologías. La era digital permite registrar, por ejemplo, la tradición oral, los idiomas y otros aspectos no verbales como los gestos, la mímica, etc.

<br>6.- La protección legal y el reconocimiento público de los creadores, portadores y transmisores del conocimiento.

<br>7.- Concibe el turismo y el mercado, siendo consciente de los riesgos potenciales de despatrimonialización y destradicionalización, como factores que pueden contribuir al fortalecimiento y/o revitalización de una manifestación cultural intangible. Una mayor popularidad puede beneficiar al bien cultural, si no se exceden ciertos límites que alteren significativamente la tradición, frente a las amenazas de la homogeneización cultural, la globalización, los procesos de mundialización y la galopante urbanización.

<br>8.- La UNESCO considera que mediante las industrias culturales pueden producirse y distribuirse bienes y servicios patrimoniales (Producción de documentos audiovisuales, Grabaciones, Documentales, Textos, Multimedia…)

<br>Desde el 2008 las noventa manifestaciones declaradas Obras Maestras del Patrimonio Oral e Inmaterial de la Humanidad por la UNESCO se integran en la Lista Representativa del Patrimonio Cultural Inmaterial. La convocatoria del 2009 incluyó setenta y seis elementos, la del 2010, cuarenta siete y la del 2011 diecinueve12. Actualmente un Comité Intergubernamental elabora los criterios de inscripción en esta lista con la inclusión de las expresiones que requieren medidas de urgente salvaguardia; para ello ha creado, además, la Lista de Salvaguardia Urgente.

<br>La Lista del Patrimonio Cultural Inmaterial no establece jerarquías; ahora bien, como ha escrito Marie Renault (2007): "…la protección del patrimonio vivo no debe reducirse de ningún modo a mantenerlo estático. No se trata tampoco de salvar prácticas del pasado que ya no tienen vida o que se encuentran fuera de su contexto…". Lo que hay que crear son las condiciones sociales y económicas que permitan su viabilidad y transmisión dentro de las comunidades y los grupos sociales. De manera que debe valorarse, tanto como la conservación, la transmisión; pero también hay que hacer esfuerzos mediante las nuevas tecnologías de la información y la comunicación, como la fotografía, la grabación digital, etc., para que dichas expresiones puedan registrarse, fijarse y pasarse a un soporte físico-material. Y en cuanto a la transmisión debiera fomentarse, primero, el apoyo institucional a los detentadores/portadores (Tesoros Humanos Vivos) de las prácticas culturales y, después, la protección de los mecanismos de traslado del conocimiento a las generaciones venideras. Hay que tener presente, no obstante, que cada transmisión, de individuo a individuo o de grupo generacional a otra generación, no sólo implica reproducción sino también pérdida, recreación e invención. De esta manera no existen versiones auténticas u originales, sino múltiples y diversas variantes.

<br>El patrimonio como memoria social: la representación del pasado y la imagen de la identidad

<br>La memoria social no es la memoria individual de las personas; es la memoria que está ligada a la pertenencia a grupos sociales y por ello se comparte, está contextualizada y dialécticamente vincula el presente y el pasado. La parte de los recuerdos que se comparten con otros eso es la memoria social. La experiencia pasada se revive en imágenes y formas de vida13. Ahora bien, si se conservan los recuerdos también se experimenta en ellos un proceso de cambio social en y desde la experiencia contemporánea. Porque el proceso de transmisión de la tradición, mediante la memoria colectiva, conduce a un proceso de reinterpretación y a nuevos significados en los contextos adecuados. La memoria social como sistema de significados y representaciones de la experiencia colectiva siempre se debate entre la relación que existe entre el pasado y el presente; si bien la representación del pasado es esencialmente polisémica y está en correspondencia con los poderes establecidos, la invención de las tradiciones y la construcción que de él hacen los diferentes grupos sociales. La memoria colectiva permite traer el pasado al presente; pero el presente, periódicamente, se construye sobre un pasado seleccionado.


<br>Son las ideas colectivas, sus materializaciones concretas, y las experiencias compartidas con otros lo que convierten a la memoria en social. La memoria colectiva deriva de la experiencia compartida; pues la memoria es el lugar donde habitan los recuerdos. Y aunque el presente es heredero de lo principal del pasado, la memoria social se construye y usa desde el presente. La memoria necesita para expresarse de referencias en términos de espacios y tiempos. En los lugares es donde se fija la memoria, la que los carga de significados tratando de evitar la acción del olvido. No hay memoria sin lugares, pero también sin imágenes, ni lugares sin memoria. La memoria colectiva preserva la herencia social y sirve de recordatorio para mantenerla viva. Implica, además, un sistema de representaciones en constante dialéctica entre el pasado, el presente y el futuro. Como ha escrito Peralta:
La función principal de la memoria es la de promover un lazo de filiación entre los miembros de un grupo con base en su pasado colectivo… La memoria permite crear una imagen del pasado que corresponde a los marcos de significación del presente…14.

<br>A través de las formas de expresión relevantes, bienes tangibles e intangibles, nos dice quienes somos, identifica al grupo, insertando nuestros yoes individuales en uno colectivo, con un anclaje en el pasado y un referente en el presente.

<br>Existe estrecha relación entre lo que entendemos por memoria social y patrimonio; habida cuenta que la memoria social sirve para reelaborar la continuidad entre el pasado y el presente, y es, como el patrimonio, resultado de una construcción social y factor mediante el que se configura la identidad de los grupos sociales, confiriéndoles sentido a su pasado y significación a su presente. Porque la cultura y el patrimonio son la base de la memoria colectiva y componentes esenciales en la conformación de la memoria social; si bien, como la memoria el patrimonio es dinámico y activo, por lo que está sometido a cambios. La memoria social, como la tradición, es cambiante y selectiva; se inventa y construye desde el presente, pero es la memoria compartida la que nos vincula al pasado, no la realidad. La realidad cambia, se transforma y modifica con el paso del tiempo. De tal manera la memoria sirve para recordar el pasado, reformulado, en el presente.

<br>Como indicó el profesor Llorenç Prats: "El patrimonio es un recurso permanente al pasado para interpretar el presente y construir el futuro"15. El patrimonio hay que abordarlo como fuente de memoria y de autoreconocimiento, pero también como formas de vida vividas. El patrimonio es por sí mismo un registro de la memoria social, de un pasado y presentes compartidos y vividos. En su vertiente inmaterial, parte esencial de la memoria colectiva, posee un gran valor simbólico. Gran parte de la memoria social se conserva no sólo en los recuerdos compartidos, sino también en las manifestaciones patrimoniales intangibles y materiales: conocimientos, saberes, rituales, prácticas sociales, formas de expresión estética, construcciones, etc. De tal manera hay que considerar el patrimonio como capital simbólico, puesto que los valores que comprenden los bienes culturales son parte fundamental de la memoria cultural de la humanidad. De aquí su capacidad de representar la memoria social y una determinada imagen de la identidad. Cuando se activa el patrimonio se contribuye a la recuperación de la memoria colectiva.

<br>La memoria social es una fuente de conocimiento en relación con las tradiciones propias. Reconocer significa identificar a partir del conocimiento o de la experiencia previa. "La memoria no es sólo retrospectiva, sino también prospectiva. Proporciona una perspectiva para interpretar nuestras experiencias en el presente y para prever lo que hay más adelante"16.

<br>La transmisión de la memoria se verifica mediante la cultura. La cultura y el patrimonio como parte de ella cambian en el tiempo y el espacio. Determinados usos del pasado se desechan cuando dejan de ser funcionalmente útiles o se consideren simbólicamente irrelevantes para la comunidad, mientras que otros, en cambio, permanecen transformados y adaptados a las nuevas situaciones. La memoria social implica construcción y representación del pasado, pero también proyección en el presente en cuanto factor generador de identidad grupal. Lo que recordamos como individuos, el pasado seleccionado y a veces distorsionado también, siempre está condicionado por el hecho de que pertenecemos a un colectivo que tiene existencia en un contexto cultural concreto. La memoria del pasado colectivo, reflejada en diferentes formas en los referentes patrimoniales, está estrechamente unida al sentimiento de identidad. De hecho es la memoria y la experiencia compartida la que determina la identidad, una ligazón con un pasado común que, como han puesto de manifiesto Eric Hobsbawm y Terence Ranger con su teoría de la invención de las tradiciones, se reactualiza constantemente y se construye o inventa desde el presente17. Ahora bien en el presente, en todos los presentes, existe una memoria viva del pasado, o representación de él, permanentemente recreado desde la contemporaneidad.

<br>Una idea fundamental en el trabajo de Maurice Halbwachs es que el recuerdo y la memoria no se conciben al margen de sus correspondientes marcos sociales o marcos de la memoria, el espacio y el tiempo, que funcionan como puntos de referencia en relación con los grupos de los que formamos parte. Un planteamiento equivalente sobre esta cuestión, los contextos relacionales, desarrolló varias décadas después el antropólogo James Fentress.

<br>El patrimonio supone una representación  de la memoria social del grupo, lo que se expresa estableciendo vínculos y afectos con la tradición. Quienes bombardearon los Budas de Afganistán, los talibanes, se equivocaron en los fines perseguidos. No sólo por la destrucción que perpetraron de unos bienes patrimoniales, sino porque creyeron que con la desaparición de las formas materiales desaparecería su recuerdo y lo que representaban para los budistas y la humanidad. El soporte de la memoria social no está únicamente en lo material, pues de igual modo los grupos humanos cargan los lugares de  significados. De tal manera el espacio culturizado, cargado de significados sociales, es una poderosa fuente de memoria social. Las imágenes espaciales, y no sólo los iconos o testimonios materiales, desempeñan un importante papel en la memoria colectiva. El recuerdo y la evocación de las imágenes desaparecidas, pero especialmente el espacio que ocupaban, están cargados de sentidos. Es decir, los marcos espaciales están connotados de valores intangibles y de significación simbólica. Reconocer es recordar y recordar siempre condensa ciertas cargas de emotividad. Los bienes culturales como memoria pero también como patrimonio vivo; las ideas y sus significados comúnmente permanecen y se transmiten existan o no los testimonios materiales que las representan. Ahora bien, a diferencia de la memoria histórica "…la memoria colectiva sólo retiene del pasado lo que aún queda vivo de él o es capaz de vivir en la conciencia del grupo que la mantiene". La memoria colectiva, que pone el énfasis más en la categoría espacio que en el factor temporal, es un continuum sin separaciones claramente trazadas. De tal manera el presente no se opone al pasado ni al proceso que representan las costumbres sociales y la transformación que progresiva y secuencialmente experimentan todas las sociedades y los grupos sociales18. El patrimonio cultural de un grupo social es la memoria de su cultura seleccionada, la memoria grupal que se transmiten las generaciones, situada invariablemente en la frontera de la sociedad de los vivos y la de los muertos. Es decir, la memoria interconecta y hace compatibles el presente y el pasado.

<br>Se ha considerado que la escritura es condición fundamental para la existencia de la memoria; es más, hay quienes piensan "que sin escritura no hay memoria". Es una idea equivocada pues, como acabo de referir, existen otras formas de memoria que no se transmiten mediante el texto escrito. La memoria social también se transmite mediante las imágenes, el uso de la imaginación y oralmente. En las construcciones, los monumentos, museos, las tradiciones, los rituales, las prácticas y los usos sociales, en los sistemas de creencias y valores, en la tradición oral, etc., se encuentran importantes fuentes de la memoria y expresiones del patrimonio colectivo. La oralidad es una forma universal de transmisión de los conocimientos y de la memoria colectiva; si bien los procesos de transmisión, lógicamente, generan cambios y variaciones, pues las culturas están vivas y son creativas. Refiriéndose a la transcripción del patrimonio oral, Jack Goody ha escrito que cuando conservamos el patrimonio se trata en último término de una o varias versiones entre otras múltiples19. En función de ello aconseja que ninguna deba asumirse como "auténtica", ya que todas son representativas del género en una cierta época y de un cierto lugar. Es suma, la transmisión oral es un útil medio para conservar parte de la memoria colectiva.

<hr>El dilema de los nuevos usos de los bienes culturales

<hr>Algunos autores han considerado que hay que repensar el patrimonio y sus usos sociales como memoria y factor de progreso. Vinculan el patrimonio a otras redes conceptuales, tales como el turismo, el desarrollo y la mercantilización20. Porque el patrimonio no es únicamente el pasado, sino que incluye asimismo otros bienes actuales y determinadas formas de vidas de diversos sectores sociales. Por ello hay que tratar de crear condiciones desde la política y el conjunto de la sociedad para que todos los grupos de ella puedan compartir y encontrar significativos los distintos patrimonios. Es decir, se necesita una reconceptualización del patrimonio y de la política cultural. Un proceso de resemantización del patrimonio alejado de su noción elitista. Apenas se han tenido en cuenta los capitales simbólicos de los grupos subalternos y existe una jerarquía de los bienes culturales, que otorga una mayor valoración social al arte que a la artesanía, a la música culta que a la tradicional, a la medicina científica que a la popular, a la cultura escrita que a la oral. A tal estado de cosas ha contribuido, también, el hecho de que la memoria popular frente a la oficial es una memoria corta, o contramemoria como quería Foucault, desvalorizada y sin los recursos necesarios para alcanzar ni la profundidad histórica ni el reconocimiento social.


<br>Los usos sociales del patrimonio tienen que ver con los procesos de transformación que los actores sociales hacen, desde el presente, sobre los variados referentes patrimoniales. Cada sociedad utiliza, recrea y crea el patrimonio, que adquiere diversos usos sociales según los intereses de los grupos y los contextos sociales, políticos, económicos e ideológicos. Cada grupo social usa y transforma los bienes culturales para convertirlos en recursos. Y cada sociedad, en cada momento temporal, otorga a los bienes culturales los significados sociales que considera; pues como los referentes patrimoniales operan como símbolos culturalmente creados son susceptibles de manipulación.
El patrimonio, cada día en mayor medida, es usado socialmente. Se trata de un recurso (construcción social) en permanente reformulación, que mediante el valor de cambio se ha convertido en un producto propio de los nuevos hábitos de consumo en la sociedad del ocio. Es un instrumento de desarrollo social y económico, pero también un medio de identificación. Es decir la cultura y su parte más significativa, el patrimonio, como recurso social y oferta turística capaz de generar riqueza especialmente en los ámbitos locales donde no existe el gran patrimonio. Pero el valor del patrimonio está en lo que significa, no tanto en las formas que reviste. De manera que el objeto, material o social, significa algo más allá de las formas: la idea que lo generó, los usos y funciones para los que se creó, el contexto en el que se originó…


<br>Dos concepciones sobre el patrimonio: la que enfatiza en su interés mercantil y la que lo hace en su capacidad simbólica de legitimación de identidades. Los referentes patrimoniales tienen un valor de uso (identidad) y un valor de cambio (mercado). El valor de uso remite a funciones interiores de la comunidad en relación con la memoria colectiva. Y el valor de cambio refiere las funciones exteriores (los usos turísticos). En una sociedad consumista en la que, en razón de la ley de la oferta y la demanda, todo se vende y compra, los bienes patrimoniales se han convertido en un recurso susceptible de desarrollo y en una mercancía. Dos discursos, pues, el identitario (patrimonio de uso) y el productivista (patrimonio de consumo). Opera el primero como marcador étnico y como factor potencial de desarrollo social y medio de transformación económica el segundo. De manera que el patrimonio cultural se encuentra en un dilema que fluctúa entre la preeminencia de los valores de uso, identificación de la memoria colectiva, y la prevalencia de los valores como producto. Ahora bien, si es cierto que determinados modelos de desarrollo, de activación y puesta en valor del patrimonio, especialmente desde una perspectiva economicista, encierran ciertos riesgos; en general se parte de una falsa premisa que contrapone los valores turísticos del patrimonio con los de la identidad. De acuerdo con LLorenç Prats, en algunos casos la comercialización del patrimonio, su valoración en el mercado, no sólo no va contra la identidad, sino que a veces contribuye a mantenerla21. Es decir, la puesta en valor del patrimonio con fines turísticos y de desarrollo no tiene porque ir necesariamente contra la identidad; a veces ocurre lo contrario: puede ayudar a recuperarla, a activarla o incluso a reformularla. Parece un planteamiento erróneo, en consecuencia, considerar que turismo e identidad tengan que excluirse en todas las circunstancias. Una apuesta sostenible y racional por la rentabilidad del patrimonio, como producto susceptible de comercialización, no debiera afectar negativamente a la identidad. Es más, con la recuperación del patrimonio y su valoración se contribuye a concienciar y a rescatar la memoria. Se trata, al fin, de una estrategia de adaptación social y económica, pero igualmente evidencia una forma de "resistencia cultural" o respuesta local frente a los procesos de homogeneización global22.
Lo que parece evidente es la coincidencia en el tiempo de la valoración social del patrimonio cultural como recurso y la expansión del fenómeno turístico, una forma moderna de ocupar el tiempo de ocio. Del mismo modo que las culturas indígenas y los grupos nativos, las sociedades locales en el medio rural europeo reivindican el derecho a controlar el acceso, el uso y la valoración de sus modos de vida más significativos. Porque cuanto se activa el patrimonio se recupera la memoria colectiva, se toma conciencia de pertenencia y se incrementa la autoestima de los grupos de referencia. La construcción del patrimonio cultural como recurso turístico (fiestas y rituales, artesanías, gastronomía, conjuntos históricos, arquitectura vernácula, paisajes culturales…) y factor de desarrollo se ha potenciado significativamente en las sociedades industriales en correspondencia con los movimientos de población en busca del ocio. En los ámbitos locales se trata de crear un producto con valor económico y social mediante la patrimonialización de las formas de vida y sus manifestaciones más singulares. Ahora bien, la cultura y el patrimonio en su concepción antropológica no pueden disociarse de la vida de las colectividades. La comercialización turística de la riqueza cultural requiere la negociación y el acuerdo de las comunidades, porque la cultura y el patrimonio son los principios fundamentales en los que se sostiene la memoria social. Como acertadamente recogen las indicaciones de la Comisión Mundial de Cultura y Desarrollo, bajo el título de Nuestra Diversidad Creativa: "…el patrimonio cultural no debe convertirse en una simple mercancía al servicio del turismo…, sino que debe establecerse una relación de apoyo mutuo…"23.

<br>Como acabo de sugerir la incorporación del patrimonio, su recreación o simulación, al mercado turístico implica, a veces, que los grupos sociales reactiven sus tradiciones. Es decir, la valoración productivista del patrimonio no tiene porque ir contra su valor simbólico. El patrimonio como factor generador de identidad es compatible con su valor en términos de recurso turístico. Debieran priorizarse, no obstante, las funciones y los valores de uso (referente simbólico y de identidad) frente a los de cambio. Ahora bien, los bienes culturales hace ya tiempo que entraron en la lógica del mercado. De manera que hay que tratar de conjugar su valor de uso (marcador de la memoria colectiva) con el valor de mercado (producto cultural comercializable). Debiera compatibilizarse, consecuentemente, la dimensión simbólica del patrimonio con el discurso económico y social, habida cuenta que por una parte es una representación de la identidad social; y por la otra se considera un factor de desarrollo que puede contribuir a mejorar la calidad de vida de las gentes asentadas en el hábitat rural24.

<br>Como han explicado entre otros autores Néstor García Canclini y Agustín Santana, hay que tener en cuenta los efectos negativos y las consecuencias que puede causar la sobreexplotación del patrimonio. El desarrollo urbanístico y el turismo como fenómeno de masas pueden alterar las funciones y los significados convencionales de los referentes patrimoniales, porque ciertos cambios pueden transmutar la realidad. Las representaciones etnográficas y las performances culturales, asimismo, pueden contribuir a fosilizar la cultura o a vaciarla de contenidos. El reducir el patrimonio a mero producto de consumo, la idealización de la realidad, el patrimonio-ficción, representado para los otros, o el convertir las zonas deprimidas social y económicamente en reservas naturales y "culturales" favorecen la despatrimonialización. Error mayor es creer, sin embargo, que como si se tratara de fotos fijas, las culturas deben permanecer ancladas en el tiempo y en una determinada tradición; es decir, a manera de museos o recuerdos fósiles del pasado. Es lo que ocurre con algunos centros históricos convertidos en imágenes estáticas y en idealizados escenarios que utópicamente pretenden reproducir o remedar una supuesta tradición o configuración urbanística perdida. Poblaciones-fachadas como la Alberca (Salamanca), Santillana del Mar (Cantabria), Castrillo de Polvazares (León), Pals (Gerona) y otras tantas diseminadas por los territorios de España ejemplifican claramente esta idea. Y aunque los espacios y los bienes culturales se resignifican y adquieren usos diversos en relación con los nuevos fenómenos de patrimonialización de la cultura, las representaciones también se muestran frecuentemente bastardeadas, cuando no se trata de invenciones exnovo. Como considera García Canclini la idea de autenticidad y de lo auténtico es una invención moderna y la mayoría del patrimonio que se consume actualmente es resultado de un simulacro, lo que se denomina el patrimonio fingido: representaciones, recreaciones teatrales, reconstrucciones materiales, réplicas de todo tipo, souvenirs, etc. Existe una tendencia general a idealizar el pasado y a cargar sus testimonios de un cierto halo de sacralidad. Se olvida que los bienes culturales son el resultado de una selección renovada continuamente. Lo importante, en cualquier caso, no debiera centrarse tanto en rescatar el patrimonio supuestamente auténtico, como en el culturalmente representativo. No es lo mismo la realidad que las representaciones que se hacen de ella.

<br>Por otra parte, la "mercantilización" de la cultura posibilita que algunos grupos permanezcan en sus comunidades y no tengan que emigrar. El patrimonio cultural asociado al desarrollo contribuye a crear industrias culturales y a ampliar ámbitos de lo social y lo económico en relación con el fenómeno de patrimonialización de la cultura. La puesta en valor de los bienes patrimoniales, aparte, puede significar beneficios en general y especialmente en los entornos de las culturas locales. Un turismo sostenible contribuye a la conservación del patrimonio, al tiempo que se convierte en vehículo de desarrollo social. El interés y los nuevos usos turísticos del patrimonio son innegables. A nivel local se están activando determinadas tradiciones, testimonios del pasado y creaciones del presente, para contribuir a la creación de empleo y a fijar la población en el medio rural. LLorenç Prats25 se pregunta si la ecuación turismo+patrimonio=desarrollo. Y contesta: depende. Depende de múltiples y variados factores; pero considera que el turismo, especialmente en los planos locales, puede representar diversificar las fuentes de ingresos, un factor de cohesión social, relevancia política y la idea de crear una imagen colectiva. Lo que, en principio, no tiene porque producir trivialización de los discursos sobre el patrimonio, ni tampoco la mercantilización de las identidades.
Lógicamente determinados niveles de "turistización", cuando se rebasa la capacidad de soporte, puede implicar riesgos. El exceso de explotación mercantil contribuye, qué duda cabe, a desvirtuar la realidad con la inevitable pérdida de funciones y significados en aras a una mal entendida espectacularización de la tradición. Por ejemplo, escenificadas algunas de nuestras manifestaciones significativas pensando más en la percepción exterior, el turismo, que en la interior, la memoria colectiva, se contribuye a transformarlas en creaciones artificiales. En Extremadura en los últimos años algo de esta teatralización de la tradición está ocurriendo, justificada por una hipotética rentabilidad económica, más mitificada que real, con ciertas celebraciones festivas de mayor singularidad y con tradiciones tales como el "Pero-palo", de Villanueva de la Vera, o más especialmente con los "Empalaos" de Valverde de la Vera. Rituales cíclicos, sobrecargados de exotismo primitivista, convertidos hoy en performances para los turistas. En estos y en otros casos asistimos a un paulatino pero progresivo proceso de "desnaturalización" al reinventarse tales celebraciones en exóticas escenificaciones saturadas de anacrónica ruralidad. Ante tal estado de cosas comienza a extenderse la idea, como respuesta cultural, de festejar los rituales con significados distintos en dos fechas diferentes: una, para los foráneos, el turismo (los otros); y otra, en días no festivos, para los de dentro, la comunidad local. La celebración durante la primera fecha consiste, básicamente, en una representación de la segunda, la vivida y experimentada por la comunidad26.

<br>En el contexto de una sociedad globalizada y en el mercado mundial Cultura, Patrimonio y Turismo no son esferas separadas. El llamado turismo sostenible, o ecoturismo, se trata de un cambio de actitud sobre los bienes patrimoniales para minimizar los impactos en las sociedades receptoras. La cultura, como escribió Davydd J. Greenwood se ha convertido en una mercancía27. Ahora bien, el turismo que genera el patrimonio en los entornos locales debe contemplarse como una fuente de ingresos complementaria, en concordancia con este tipo de recursos limitados y no renovables que son los patrimoniales. En este sentido y en nuestro contexto sociocultural la filosofía de los programas Leader, en los que el patrimonio y la tradición se asumen como factores de progreso, está focalizada a la estimulación de las economías locales. El planteamiento se fundamenta en la activación de la oferta patrimonial valorando todo tipo de recursos, naturales y culturales, a fin de obtener un producto comercializable. Esta modalidad de respuestas locales, frente a los fenómenos de la globalización, requiere una competente gestión y especialización en las disciplinas relacionadas con los bienes culturales. La aplicación práctica del conocimiento antropológico, investigación e intervención planificada, y la implicación del investigador en la sociedad analizada, son premisas necesarias para lograr una eficaz acción que permita transmitir a las generaciones venideras, de manera armónica, un medio natural y social con perspectivas de futuro.
La valoración del patrimonio, tangible e intangible, paisajístico, monumental, arqueológico, artístico o etnográfico, debe realizarse teniendo en cuenta las estrategias de desarrollo territorial. Lo que supone depender, antes de nada, de una planificación previa y del diálogo constante con la comunidad de referencia. El trabajo de campo, la estrecha relación que debe existir entre el investigador y los investigados, es un instrumento imprescindible cuando se trata de obtener éxito social y económico en los planes de gestión e intervención del patrimonio cultural.  </p>

                                    </div>


                                    </div>




    </div>
    <!-- /.container -->

<?php include('footer.php');?>
