<!DOCTYPE html>
<?php include('header.php');?>

    <div class="container">

        <div class="bg-faded p-4 my-4">
          <!-- post 1-->
                  <div class="bg-faded p-4 my-4">
                    <div class="text-center mt-4">

                          <h2 class="my-2">Nueva Ruralidad desde dos visiones de progreso rural y sustentabilidad: Economía Ambiental y Economía Ecológica</h2>
                          <div class="bg-faded p-4 my-4">
                                      <hr class="divider">
                                      <h3 class="text-center text-lg text-uppercase my-0">Mara Rosas-Baños</h3>
                                      <hr class="divider">

                                      <p>Define la vida rural en la actualidad, estableciendo que la tradicional vida rural, asociada a la actividad agrícola y ganadera, hoy en día se basa en la estrecha relación con la vida urbana, donde las aldeas campesinas desarrollan gran parte de sus vidas cotidianas y sus relaciones sociales en centros urbanos y donde la actividad agropecuaria ha sido remplazada en gran parte por actividad industrial.  </p>
<p>Revisa el texto original <a href="http://www.scielo.cl/scielo.php?pid=S0718-65682013000100012&script=sci_arttext">aqui</a></p>
                                      <img class="img-fluid float-center hidden-md-down " src="img/productor.jpg" alt="">
                                      <hr></div></div>

                                      <div class="cuerpo p-4"> <p>Resumen: El desarrollo local desde principios de los años noventa se encuentra influenciado por una corriente sociológica que propone el replanteamientoteórico de lo que la teoría ha llamado el sector rural. La Nueva Ruralidad en superspectiva latinoamericana ubica aspectos de cambio fundamental en el territoriorural: encadenamientos urbano-rurales, el empleo rural no agrícola, la provisiónde servicios ambientales, las certificaciones agroambientales o "sellos verdes", lospueblos como centros de servicios, el papel activo de las comunidades y organizaciones sociales, y la diversidad ecológica-cultural como patrimonio (Rojas, 2008).El objetivo de este documento es mostrar que existe un debate al interior de estacorriente que ha derivado en dos modelos de desarrollo regional sustentable contrapuestos, el enfoque basado en la participación del mercado y el que aboga por laautonomía, la autogestión y la autodirección del progreso de las comunidades rurales.

<hr>Palabras clave: Nueva Ruralidad, desarrollo local, progreso sustentable, economía ambiental y economía ecológica.



<hr>Introducción

<hr>El desarrollo local desde principios de los años noventa se encuentra influenciado por una corriente sociológica que propone el replanteamiento teórico de lo que la teoría ha llamado el sector rural. La Nueva Ruralidad, NR en su perspectiva latinoamericana ubica aspectos de cambio fundamental en el territorio rural: encadenamientos urbano-rurales, el empleo rural no agrícola, la provisión de servicios ambientales, las certificaciones agroambientales o "sellos verdes", los pueblos como centros de servicios, el papel activo de las comunidades y organizaciones sociales y la diversidad ecológica-cultural como patrimonio (Rojas, 2008).

<br>La perspectiva que impulsó la creación de empresarios agrícolas y la tecnificación del campo que ha sido objetivo de los modelos de desarrollo regional durante más de setenta años retomó un impulso con políticas guiadas por la teoría económica que hoy rige la política nacional e internacional, la teoría económica neoliberal. La necesidad de incorporar cuestiones sobre sustentabilidad de procesos económicos obligo la especialización de esta corriente teórica al ámbito de la naturaleza conformándose así la propuesta ortodoxa de la economía ambiental y una serie de sugerencias del desarrollo regional que implican la gestión de servicios ambientales y la incorporación del "capital social". Concepto que se refiere a las posibilidades productivas que devienen de una organización social que posee una combinación particular de lo concreto-abstracto que posibilita relaciones de confianza, reciprocidad, solidaridad y cooperación, relaciones que se materializan en instituciones comunitarias. El capital social es una construcción teórica ortodoxa cuyas aportaciones recientes se deben a Colman y Putman, quienes en una contextualización errónea (Fine en Burkett, 2001) tratan de dar al concepto de capital de la economía neoclásica una aproximación a lo social con una retroalimentación que se genera desde el punto de vista individualista. El capital social es utilizado como un complemento al capital humano que potencializa la producción; por tanto, reduce la complejidad de relaciones sociales y lógicas en las que se encuentra inmersa la producción comunitaria a un agilizador de la productividad.

<br>La Economía Ecológica, EE como contraposición a la economía ambiental, enfatiza el hecho de que los mercados no pueden asignar valores a los recursos naturales y afirma que los sistemas productivos campesinos son energéticamente más eficientes y generan un menor impacto. La EE, plantea la necesidad de un enfoque transdiciplinario en la solución de conflictos sociales, ecológicos y económicos, además de que parte de la aplicación de principios éticos que guían la toma de decisiones y la construcción de alternativas. La Economía Ecológica propone que la dirección de las comunidades rurales en la búsqueda de soluciones a sus conflictos sociales y ambientales se acompañe de un dialogo de saberes por parte de universidades y centros de investigación. Sus fundamentos metodológicos: pluralismo metodológico y apertura histórica posibilitan la interacción de diferentes posturas teóricas y metodológicas.

<br>El objetivo de este documento es mostrar que existe un debate al interior de esta corriente que ha derivado en dos modelos de desarrollo regional contrapuestos, el enfoque basado en la participación del mercado y el que aboga por la autonomía, la autogestión y la autodirección del camino progreso de las comunidades.

<hr>Ruralidad y Nueva Ruralidad

<hr>La visión sociológica de la ruralidad, que surge en Europa y tiene un desarrollo más acabado en Estados Unidos a mediados del siglo XX, destaca por un lado, la relación directa entre lo rural y lo agrícola y, por otro, ubica lo rural como una categoría residual en los albores de la industrialización. Al cambiar las exigencias que en América Latina el sector industrial hacía a lo rural, y considerando el regreso de la dinámica económica globalizadora que ha modificado la estructura productiva y su base material en los últimos treinta años, es menester considerar también las nuevas exigencias y formas de vinculación entre ambos espacios. La Nueva Ruralidad se propone el estudio precisamente de esa nueva relación y sus efectos en el territorio rural: efectos socioeconómicos de la emigración en las comunidades; pobreza; estrategias productivas; diversificación, gestión sustentable de recursos naturales y la adquisición de capacidades para la colocación de productos al mercado y movimientos sociales cuyo principal reclamo es la autonomía.

<br>La interpretación de esos fenómenos marca una línea que separa a los teóricos de la Nueva Ruralidad. Por un lado, están quienes ven los efectos de la globalización en el territorio rural como una agudización de la crisis, en términos de desestructuración de las relaciones sociales en las comunidades por el efecto del individualismo, profundización de la pobreza, explotación, degradación ambiental, proletarización y ven a la pluriactividad como una estrategia de supervivencia y resistencia, "una forma de aferrarse a la tierra y evitar su proletarización, ya que solamente los campesinos más ricos, son una minoría, han sido capaces de usar esta diversificación como una estrategia de acumulación". (CEDRSSA, 2007: 41)Por otro lado, quienes conciben la construcción de estrategias de acumulación no capitalista como producto de la fortaleza de la estructura social comunitaria que posibilita la adquisición de nuevas capacidades productivas en términos de negociación y de lucha, a través de los movimientos sociales reivindicando la autonomía. La implementación de estas estrategias busca mantener activo un sistema de producción que se va innovando constantemente y cuya fortaleza radica en la organización política y social. La pluriactividad, diversificación de actividades económicas dentro de las unidades familiares campesinas y las comunidades es una alternativa a la respuesta que ofrece la globalización a una minoría que podría formar parte del proletariado, una alternativa que genera oportunidades que los ayuda a mantenerse como dueños de sus medios de producción y salvaguardar sus estilos de vida y los ecosistemas de que dependen (Barkin, 2001, 2004)."Para algunos autores, hubo una tendencia fuerte hacia el multiempleo y la pluriactividad como una estrategia tendiente a captar ingresos extra prediales no agrícolas (off-farm activities) canalizables hacia inversiones en la explotación de modo tal de continuar en el campo" (Tapella, 2004:6)

<br>El punto de partida de ambas perspectivas es que la noción de lo rural ya no tiene valor explicativo. Las actividades en las sociedades rurales son mucho más complejas que las visiones que la producción agropecuaria, bajo el marco de la globalización del capital. La vida rural, tradicionalmente asociada con la actividad agropecuaria, abriga ahora una diversidad de actividades y relaciones sociales que vinculan estrechamente las aldeas campesinas con los centros urbanos y la actividad industrial (Cartón de Grammont, 2004:279). La importancia del espacio rural se incrementa y también se transforma por el papel que juegan actualmente las comunidades indígenas y campesinas en la gestión sustentable de los recursos naturales, no solamente porque ellas se encuentran en zonas de importancia natural estratégica sino por el conocimiento que han adquirido a través degeneraciones de su entorno y las innovaciones que en cuanto a formas de producir surgen en ellas con la colaboración de facilitadores de tecnología como ONGs, asociaciones civiles e instituciones de investigación. Es precisamente el análisis de la coevolución de las sociedades rurales no capitalistas con la naturaleza lo que la Economía Ecológica necesita incorporar a su cuerpo teórico para generar alternativas.

<br>Es posible establecer una separación de las condiciones que enfrentan los diferentes espacios rurales clasificando sus opciones en cuanto a empleo y producción. Por un lado, el creciente interés de los Estados por llevar inversión extranjera y tecnología industrial a la producción agrícola ha generado una dinámica de producción como extensión del sistema de producción capitalista, proletarizando algunas de las zonas en las que se ha desarrollado esa dinámica productiva.

<br>"Para Edelmira Peréz, el mundo rural se encuentra inmerso en una profunda crisis, cuyas expresiones van desde el ámbito productivo y comercial, hasta las formas tradicionales de articulación social pasando por el desprestigio de las actividades agrícolas y la desmotivación de la población rural" (CEDRSSA, 2006:48) Desde esta perspectiva la Nueva Ruralidad identifica la pluriactividad rural como un medio de obtención de ingresos salariales y la supeditación al sistema de producción capitalista. Para Cartón de Grammont, los campesinos no tienen opciones de mejorar su condición de vida con el mantenimiento de la producción campesina; para él, "el proceso de modernización de la agricultura no conllevó a la desaparición de las unidades de producción de los campesinos pobres, no por su arraigo cultural a la tierra, sino por la inexistencia de alternativas de trabajado asalariado y de políticas públicas que les aseguren la posibilidad de abandonarla actividad agrícola." (Cartón de Grammont 2004:284). Esta "nueva" noción considera la permanencia de la dualidad de la agricultura y del espacio rural así como el aumento de la pobreza en la zona rural como resultados de la incapacidad de la organización tradicional de responder a los retos de la integración internacional. Existe un doble discurso, en relación a lo nuevo y lo viejo del estudio de lo rural en ese planteamiento. Por un lado, se hace hincapié en las transformaciones de tipo material, basados en los grados de integración entre los mercados rural y urbano, y se explica una nueva relación campo-ciudad. Por otro, esta explicación sólo aplica a un segmento de la sociedad rural, la explotada y proletarizada bajo el capital en zonas rurales. Su interés se enfoca en la crisis, no en las posibilidades que actualmente las mismas comunidades están construyendo para salir de ella, porque esta perspectiva mantiene la vieja idea de que las propias comunidades no poseen conocimientos suficientes para auto determinarse, entonces ¿qué es lo realmente ha cambiado en el territorio rural?

<br>Si partimos de la perspectiva oficial podemos dar cuenta de que existen cada vez mayores segmentos de población rural excluidas de toda posibilidad de integración al mercado de trabajo capitalista, la distribución del ingreso no ha cambiado o aún ha empeorada; incluso cuando en el caso de México ha existido una tendencia al incremento de la pobreza en zonas urbanas mayor que en las rurales, el acceso a la educación y a servicios que debería de existir por parte de los gobiernos federales y locales es en extremo limitada en las comunidades indígenas y campesinas. "Por ejemplo, en Perú un alto porcentaje de los habitantes rurales carecen de cédula de identidad, requisito básico para el ejercicio de derechos ciudadanos elementales, así como para el acceso a diversos servicios públicos. En Bolivia, hasta mediados de los años noventa, vastos sectores (rurales) del territorio nacional ni siquiera habían sido incorporados en una unidad político-administrativa, es decir, eran espacios invisibles para el Estado. En Colombia, por causas conocidas, el Estado simplemente no tiene presencia ni siquiera formal en muchos municipios. En Chile, el Estado se ha negado persistentemente a reconocer constitucionalmente a los pueblos indígenas.

<br>Y en toda la América Latina rural, las mujeres están lejos de haber alcanzado una condición plena de ciudadanía" (Schejtman y Berdegué, 2004:16)Los programas de gobierno siguen tratando de imponer lógicas y métodosajenos a las comunidades y contrarios a la gestión sustentable de recursosnaturales, América Latina se caracteriza por ser el continente que muestra los índices más altos de concentración de la tierra, lo que pone en cuestión la idea de que las reformas agrarias han perdido vigencia (Tejo, 2003).

<br>La novedad rural que surge al mismo tiempo como una alternativa es la generación de estrategias por parte de las comunidades indígenas y campesinas de progreso autónomo. No consisten en la adopción de los modelos de desarrollo del sistema dominante que no derivan en una adhesión a la sobrepoblación fluctuante, latente ni estancada en el mercado de trabajo. Por eso, se puede empezar a repensar este sector de la sociedad compuesto de nuevos sujetos sociales, capaces de construir sus propios modelos de desarrollo. Esto hace necesaria una especificación, no se arguye que la sociedad rural en su conjunto se encuentren en dicha dinámica, pero se reconocen los aportes de las comunidades que se encuentran generando alternativas.

<br>La Nueva Ruralidad provee una visión distinta del núcleo del sector rural, -las comunidades campesinas e indígenas-, donde están surgimiento nuevas modalidades económicas; ecológicas; auto-gestivas; auto organizativas; y autonómicas de una gran cantidad de comunidades que actualmente presentan una combinación entre métodos tradicionales con innovaciones técnicas que posibilitan una mejora en sus términos de intercambio y por tanto, un incremento en su nivel de vida -entendido en los propios términos de las comunidades-. (Barkin y Rosas, 2006; Toledo y Altieri, 2011; Toledo, 2006 Martínez-Alier, 2004; Santiago y Barkin, 2006).Al centro de esta visión esta el reconocimiento de una cosmovisión que exige la cooperación entre comunidades que genera redes para fortalecer una economía que se encuentra inmersa en la totalidad de las relaciones sociales conducentes a un equilibrio entre la actividad humana y la natural.

<br>Las estrategias productivas de muchas comunidades indígenas y campesinas gozan del reconocimiento internacional, debido al manejo sustentable de los recursos naturales, como es el caso de las Empresas Comunitarias Forestales (Bray y Merino, 2004). Anteriormente se consideraban atrasadas y sin posibilidades de subsistir en un sistema donde se privilegia la acumulación de capital y la generación de ganancias. Estas estrategias van tomando mayor relevancia conforme se evidencia el significado de la perdida de ecosistemas.

<br>Sus propuestas estratégicas no se constituyen en repliegue; más bien, son enfoques para construir nuevas estructuras sociales y reposicionar a las comunidades en sociedades capaces de integrar sus miembros en un proceso organizado de avance hacía el bienestar y solidaridad. La idea de que las comunidades rurales pierden sus características tradicionales en su contacto con el sistema capitalista resulta ser una visión demasiado simplista de un hecho que ha estado presente a lo largo del desenvolvimiento de los espacios rurales. Las comunidades siempre han tenido en diferentes grados la influencia de instituciones que procuran homogeneizar la ideología a su interior, pero la resistencia no puede interpretarse simplemente como rechazo (Wolf 1987). "La memoria histórica de los pueblos indígenas ha estado ligada a las instituciones políticas coloniales y a las instituciones que han sido parte de la formación del Estado. Los indígenas, sin embargo, han reformulado estas instituciones para formar memorias sociales e identidades alternativas. A través de la creación de hegemonías locales y con base en su experiencia histórica asociada a la explotación y la opresión, los indígenas han creado nuevas fórmulas culturales y políticas para construir proyectos sociales alternativos y reclamar derechos ante el Estado" (Aquino, 2003:71).

<br>El término de "capital social" se refiere precisamente a las posibilidades productivas que devienen de una organización social que posee una combinación particular de lo concreto-abstracto que posibilita relaciones de confianza, reciprocidad, solidaridad y cooperación, relaciones que se materializan en instituciones de cooperación comunitaria. Sin embargo, este término de "capital social" utilizado para referir las ventajas de la producción comunitaria en cuanto organización, simplemente reduce la complejidad de relaciones y lógicas en las que se encuentra inmersa la producción comunitaria a un factor de producción, tal como la teoría neoclásica reduce a simples factores tanto la participación del hombre como de la naturaleza en la producción.

<br>Las comunidades indígenas y campesinas hoy siguen luchando por su autodeterminación y ascenso en su calidad de vida. Aunado a una serie de nuevas propuestas comunitarias en las que podemos ubicar al movimiento del Ejercito Zapatista de Liberación Nacional (EZLN), el desarrollo etnoecológico de Toledo, el desarrollo comunitario de Barkin y el de Leff. "La gestación de la propuesta autonómica ha madurado de tal forma en Bolivia que los pueblos indios que ahí coexisten y que han sido protagonistas en las luchas de los cocaleros y el movimiento sindical de los ochenta y noventa, hoy no solamente mandan el ejercicio de la autonomía sino la creación de un Estado pluriétnico en el que se funden de raíz las bases que fundamentan jurídicamente la constitución política" (López y Rivas, et al. 2007:48) Pero no solamente en Bolivia están construyéndose las bases sólidas de lucha autonómica; en Ecuador fue posible la destitución de los presidentes Abdalá Bucaram y Jamil Mahuad; también se derrotó electoralmente la candidatura de Alberto Fujimori en Perú. Estos movimientos se caracterizan por la participación política, social y económica cada vez más informada y por su plena seguridad en que es solamente a través de la búsqueda de la autonomía como los espacios rurales podrán salir de las condiciones históricas de subdesarrollo y pobreza en que los modelos oficiales de desarrollo han arrinconado a las comunidades rurales. La lucha por la autonomía indígena no es nueva, existe una tradición de autogobiernos de facto establecidos con mayor o menor éxito por las comunidades rurales, pero tiene matices que le dan un nuevo carácter al incorporar otros actores de la vida nacional (López, et al 2007).

<br>Este reposicionamiento hasta el momento se ha manifestado en la adaptación de una serie de proyectos como: el incremento en el número de empresas comunitarias forestales y eco turísticas, donde una de las más reconocidas internacionalmente es el aserradero de la comunidad de San Juan Nuevo Parangaricutiro (Michoacán, México), que ha generado cadenas productivas con la creación de 20 empresas locales de propiedad comunal. De hecho la creación de Empresas Comunales Forestales es una de las experiencias económicas más exitosa en México. Las comunidades han estado rescatando de manos de empresas rentistas, tanto privadas como estatales sus bosques; algunas de ellas están en las comunidades de: Capulpam de Méndez en Oaxaca, el ejido de Laguna Kana, Quintana Roo, San Pedro el Alto, Oaxaca, entre otras (Bray y Merino, 2004). Proyectos de producción de bienes básicos de consumo con un alto valor agregado como: la producción de carne de puerco baja en colesterol (Michoacán), producción de botanas y galletas de amaranto (Puebla), entre otros. Otras incluyen: la creación y fortalecimiento de las Áreas Naturales Protegidas que favorece la participación de los ejidatarios en la conservación y que posibilita algunas actividades productivas y la recuperación de aguas de uso doméstico para la agricultura a través de la construcción de plantas de tratamiento de aguas cuyo costo es bajo debido a que algunos materiales provienen de plástico reciclado y la mano de obra de las comunidades del Istmo de Tehuantepec, Oaxaca.

<br>Los proyectos productivos de este tipo son muestra de que las comunidades pueden gestionar sus propias actividades económicas y administrar sus recursos a través de proyectos que son exitosos debido a su organización social y política. El reconocimiento por parte de gobiernos, organismos internacionales y una cantidad creciente de consumidores de las ventajas que conllevan la forma de organización socio-económica de las comunidades en la preservación del medio ambiente, se ha manifestado por un lado, en mayor libertad de gestión de proyectos productivos propios y un incremento en la accesibilidad de gobiernos para que las comunidades sean las responsables de extensas áreas de conservación. Por otro lado, un creciente número de consumidores reconoce y valora la producción de mercancías de mejor calidad nutricional y ecológicamente producidas. El "Comercio Justo" presenta nuevos mecanismos de intercambio que buscan garantizar mayor estabilidad de precios e ingresos de los productores campesinos, con reconocimiento de una retribución para los verdaderos costos sociales y ecológicos; éste, a su vez, garantiza a los consumidores productos socialmente justos y ecológicamente responsables a precios razonables. Los principales productos que se comercian por esta vía son agrícolas, generados por pequeñas unidades productoras entrelazadas para asegurar volúmenes comercialmente viables, las cuales, participan en un mercado solidario organizado por instituciones del Comercio Justo en Europa y en otras partes. Al trasladarse a la esfera de la circulación, su venta permite a las comunidades obtener un excedente económico que es utilizado tanto para la reposición y ampliación de sus medios de producción como para el mejoramiento de condiciones de vida de la comunidad.

<br>Elementos como la diversificación productiva, uso creativo de recursos naturales y la participación local en la planeación e implementación de técnicas productivas, además de la autodeterminación, son fundamentales para entender la existencia de una relación económica diferente entre ciertos espacios rurales y el sistema capitalista (Barkin, 2001). Los sistemas de producción y reproducción social de los pequeños productores, unidades familiares campesinas y comunidades se están transformando y han originando una nueva estructura de Actividades No-proletarias Generadoras de Excedentes(ANGE) (Barkin y Rosas, 2006). Estas actividades son posibles por una combinación de factores que van desde las cuestiones de equidad de género, la sustentabilidad del medio ambiente, la generación de redes entre comunidades hasta la ampliación de canales de comercialización.

<hr>Multifuncionalidad, sustentabilidad y Economía Ecológica

<hr>Las funciones que el espacio rural realiza, no solo en su interior sino para las sociedades urbanas, encuentran relevancia a medida que crece el interés por la sustentabilidad ecológica. "La noción de multifuncionalidad de la agricultura se refiere a la totalidad de productos, servicios y externalidades creados por la actividad agrícola y que tienen un impacto directo o indirecto sobre la economía y la sociedad en su conjunto. Estas producciones tiene la característica de ser poco o mal reguladas por el mercado, en particular aquellas que tienen incidencia social o ambiental. La traducción concreta de la noción en términos de políticas públicas hace referencia a la formulación de intervenciones específicas destinadas a favorecer los aspectos positivos y a limitarlas externalidades negativas de la agricultura" (Bonnal en CEDRSSA, 2006:44).

<br>La multifuncionalidad definida en esos términos presenta la visión de la economía ambiental 1 , en tanto que ubica el problema como de determinación de valores de recursos para los cuales no existen mercados y busca la intervención pública y privada para aminorar las externalidades negativas de los sistemas de producción, tanto en el sector rural como en el urbano; también propone, a través de políticas públicas, crear incentivos económicos para que empresas contaminantes, usando el pago de servicios ambientales, fomenten la conservación en comunidades indígenas y campesinas. En esta perspectiva es que podemos ubicar también la contribución de lo que llamamos la perspectiva oficial de la Nueva Ruralidad, que plantea que la crisis del sector rural se profundiza porque "aún no comprende su papel actual y sus nuevas funciones, y así no sólo pierde su identidad sino también su población, sus modelos de organización y muchas de sus actividades" (CEDRSSA, 2006:48) Las nuevas funciones que según Edelmira Pérez tiene que adoptar el territorio rural son: el equilibrio territorial, para contrastar el despoblamiento que es motivado por los modelos de desarrollo que han obstaculizado el desarrollo rural; el equilibrio ecológico en términos de conservación; producción de agua limpia y conservación de sus fuentes; espacios de esparcimiento y actividades de recreación en entornos naturales; usos agrarios no alimentarios y sumideros de contaminantes de aire, agua y suelo (CEDRSSA, 2006).

<br>El pago por servicios ambientales es uno de los instrumentos de conservación que se ha desarrollado la economía ambiental, funciones como secuestro y almacenamiento de carbono, protección a la biodiversidad, protección a las cuencas hidrográficas y belleza escénica son el tipo de servicios que principalmente empresas privadas, están dispuestas a financiar por su valor comercial. Esta visión separa la conservación del desarrollo y puede erosionar los valores de conservación arraigados culturalmente y sinfines comerciales (Wunder, 2007). Lo anterior aunado a una serie de problemas que han surgido en la aplicación de este instrumento principalmente en los pagos además existe una restricción que obliga a las comunidades a no utilizar sus recursos naturales una vez que se han logrado los objetivos de conservación, es decir, se cuartan sus posibilidades de desarrollo. Estas son algunas de las principales razones por las que muchas comunidades rurales no están interesadas en este tipo de instrumentos.

<br>Esta perspectiva se encuentra totalmente alejada de los objetivos de los movimientos autonómicos que han surgido a lo largo de América Latina y de los logros en términos productivos que se han descrito, cumpliendo con las características de ANGE. La Economía Ecológica como contraposición a la economía ambiental enfatiza el hecho de que los mercados no son capaces de asignar valores a los recursos naturales y las externalidades son ocasionadas por el nulo interés que existe por la sustentabilidad en los procesos productivos capitalistas, donde la disminución de costos norma las decisiones de adquisición de tecnología, sin considerar aspectos ambientales. Para la economía ecológica, las externalidades son inherentes a los sistemas productivos capitalistas, porque no se utilizan simplemente factores de producción, se utilizan ecosistemas, tanto en la producción agrícola como en la producción industrial. Además este argumento se refuerza con la incorporación de la segunda ley de la termodinámica como base de análisis y evaluación de los procesos productivos en términos entrópicos. La Economía Ecológica reconoce una serie de investigaciones que desde la antropología se han realizado sobre sistemas productivos evaluados en términos de utilización de energía en comunidades rurales, que utiliza junto con factores actuales como movimientos sociales rurales que defienden de la depredación capitalista recursosnaturales, para afirmar que las comunidades indígenas y campesinas cuentan con conocimientos y un tipo de organización social productiva que favorece a la sustentabilidad y por tanto, no la relega a ser suministradora exclusivamente de servicios ambientales a las zonas urbanas.

<br>La perspectiva de la Nueva Ruralidad que podemos llamar no oficial y que es compatible con la Economía Ecológica postula cuatro principios básicos para lograr el fortalecimiento de los procesos autonómicos llevados a cabo en los espacios rurales: autonomía, autosuficiencia, diversificación productiva y gestión de ecosistemas (Barkin, 2001). Bajo estos principios, y en un contexto socio-económico adverso, las comunidades están diseñando sus propias estrategias de generación de ingresos, sus ANGE, sin tener que adoptar la organización social de la producción capitalista. Así, en lugar de ser testigos de la desaparición de comunidades locales, -lo cual, tiene previsto los análisis dominantes de la sociología y la teoría económica-, se presenta la evidencia del surgimiento de formas de sincretismo y sinergias sociales que están jugando un doble papel, al mejorar la calidad de vida de la gente y, regenerar y mantener la naturaleza.

<br>Estos avances analíticos muestran la errada conceptualización antropológica de los indígenas y campesinas como pobres semi-proletarizados, incapaces de generar procesos internos de desarrollo (Hernández Navarro, 2005). Las funciones que desde la perspectiva de algunos sociólogos son la única forma que tienen las comunidades rurales de salir de su crisis, implican nuevamente una imposición, tal como los programas oficiales hacían al tratar de imponer métodos para la modernización del campo. Pero incluso cuando actualmente están funcionando los incentivos para disminución de emisiones de dióxido de carbono y algunas empresas a través de ONGs se encuentran pagando para la reforestación de algunos bosques (mecanismo de Convenio de Kyoto), este tipo de estrategias de políticas no buscan la disminución de la pobreza rural; no es un objetivo que esté planteado tal cual y lo que llega a las comunidades por esta vía es una cantidad de dinero que es risible.

<br>Si esta producción no generara excedentes, no tendría muchas posibilidades de promover el progreso social rural y conservación ambiental al cual nos referimos. La noción de excedente es fundamental; el concepto de excedente existe bajo cualquier tipo de formación socioeconómica. Su definición es la simple diferencia entre el gasto en consumo productivo corriente y reparación del desgaste causado por las instalaciones productivas en un período de tiempo respecto al volumen de producción de ese mismo período. Según Baran (1977), el excedente se clasifica en real y potencial; el primero es la diferencia entre la producción real generada por una sociedad y su consumo efectivo. El excedente potencial es la "diferencia entre la producción que podría obtenerse en un ambiente técnico y natural dado con la ayuda de los recursos productivos utilizables, y lo que pudiera considerarse como consumo esencial. Su realización presupone una reorganización más o menos drástica de la producción y distribución del producto social, e implica cambios de alcance en la estructura de la sociedad" (Baran, 1979:74). Es precisamente la combinación de ambos tipos de excedente una forma de entender el potencial de las comunidades. Existe excedente potencial, porque el uso de los recursos naturales es limitado; no se produce en función de la cantidad de recursos que se poseen, se produce en función de la posibilidad de que futuras generaciones puedan hacer un uso parecido al actual de sus recursos.

<br>De esa manera productores y consumidores manifiestan en el intercambio de mercado una relación de intereses compartidos. Pero es necesario hacer hincapié en que estos segmentos de mercado se han abierto a través de una lucha constante, en la que se han perdido vidas, la forma tradicional en que las comunidades vendían sus productos era a través de coyotes y caciques, muchas de las comunidades que ahora pueden vender sus productos a mejores precios en los tipos de mercados mencionados lo hacen después de haber librado una batalla contra sus explotadores (Roozeny VanderHoff, 2002). Las posibilidades económicas, por el crecimiento en el mercado de un segmento de consumidores dispuestos a pagar por productos con altos valores nutricionales y producidos ecológicamente se hacen más visibles por el creciente interés de grandes trasnacionales de incursionar en ese tipo de producción. Así las comunidades rurales no solamente libran una batalla con los tradicionales coyotes, sino con grandes trasnacionales interesadas en generar productos de este tipo a través de la proletarización de las comunidades. No obstante, en esta batalla las comunidades se enfrentan con conocimientos estratégicos obtenidos por el contacto directo con su entorno, conocimientos y estructuras sociales que les permiten crear productos innovadores.

<br>El manejo de la combinación de nuevas y viejos conocimientos en la producción rural tiene una incidencia directa en el mejoramiento del uso de los recursos naturales. El conocimiento y habilidades tradicionales han generado una construcción sincrética más o menos consolidada y práctica, el dinamismo del cambio en el manejo de los recursos naturales, se presenta como parte de una visión más optimista tanto por el lado de la ocupación racional de los recursos naturales como por los niveles de bienestar. Estos son los elementos que en términos generales son base para una construcción analítica.

<hr>Conclusiones

<hr>Las transformaciones estructurales que se viven en América Latina, efectivamente dan cuenta de cambios sociales, políticos, económicos y ecológicos en las comunidades que van acompañados por movimientos sociales. La Nueva Ruralidad en la perspectiva no oficial es capaz de brindar elementos concretos que nos ayuden a entender procesos productivos y sociales básicos para empezar a consolidar una Economía Ecológica tanto en términos prácticos como teóricos.

<br>La gama de posibilidades se amplía en la medida en que las luchas autonómicas se van consolidando y van abriendo espacios políticos y económicos para sus autogobiernos. Después de este análisis de oportunidades y retos que tiene el territorio rural es justo preguntarnos si el hecho de que no existan documentados tantos casos de proyectos productivos económica y ecológicamente viables ¿es una razón para dejar de estudiar esas alternativas? y ¿qué papel deben de jugar las instituciones de investigación en el progreso social rural? Por qué al igual que las instituciones de desarrollo de los Estados nacionales, la academia ha fomentado y ha sido instrumento de imposición de modelos de desarrollo que no han funcionado por decir lo menos. Generalmente mostrando desconfianza en los procesos sociales colectivos y privilegiando los intereses económicos de personajes con poder en los territorios rurales. La perspectiva oficial de la Nueva Ruralidad indica que es menester que las comunidades adopten un tipo de actividades que desde la perspectiva de estos teóricos sacara de su crisis al territorio rural. Pero podemos seguir jugando el papel de observadores externos de fenómenos y dar recomendaciones que al final de cuentas perjudicarán las formas sociales de las comunidades. No es tiempo de respetar y aportar como acompañantes a los procesos autonómicos, porque eso es por lo que luchan los pueblos, la autonomía se entiende como procesos de fortalecimiento de identidad, cultura, territorio, derechos colectivos y establecimiento de estructuras de autogobierno.

<br>El reconocimiento de que existen estructuras productivas no capitalistas que son capaces de conjuntar la gestión sustentable con la generación de excedentes para incrementar los niveles de vida provee a la EE de un nuevo campo de estudio, que es reconocido por este paradigma pero que no ha sido explorado en términos teóricos. El análisis combinado de la Nueva Ruralidad con la Economía Ecológica nos proporcionó elementos también para situar, a través de la separación de las posiciones oficial y no oficial los requerimientos a los cuales deben de ajustarse las comunidades rurales en el modelo hegemónico de desarrollo que es el neoliberal. Deberes que las comunidades, como lo afirman los mismos teóricos se rehúsan a realizar porque lo que las comunidades rurales buscan es la autonomía, capacidad de movimiento para seleccionar sus propios procesos internos de progreso, cuestión que no se aborda aquí como una utopía, sino como una realidad para un número creciente de comunidades.

<br>Este trabajo trató de sentar las bases para la inclusión en forma analítica de las estructuras productivas comunitarias en la teoría de la Economía Ecológica cuyas cualidades de multidisciplinaria, metodológicamente plural e históricamente abierta nos ayudan a posicionarnos en acontecimientos históricos para estudiar su evolución y su adaptación con métodos no restrictivos al ámbito de la racionalidad e individualismo metodológico de la teoría económica dominante. También trata de proveer elementos que nos ayuden a diferenciar los discursos sobre lo que realmente podemos considerar como Nueva Ruralidad, dilucidando los elementos que aparentemente son nuevos en un discurso de crisis y proletarización rural viejos. Esto es importante porque de lo que se trata es de ayudar a construir el progreso social rural y no de obstaculizarlo, cómo en general se ha hecho, con falsas obligaciones funcionales en términos ecológicos, cuando las comunidades rurales son las que actualmente están poniendo en práctica la agroecología, la construcción de espacios de recreación eco turísticos y están poniendo en práctica técnicas que mejoren y conserven sus espacios rurales, pero eso a la par de la construcción de procesos productivos capaces de generar excedentes económicos que los ayuden a incrementar su nivel de vida.



<hr>Nota

<hr>1 Corriente que surge de la teoría económica neoclásica para estudiar las externalidades del sistema de producción y crear métodos de valorización de bienes y servicios que no son conmensurables.
                                      </p>

                                    </div>


                                    </div>




    </div>
    <!-- /.container -->

<?php include('footer.php');?>
